id = "silex"
name = "Silex"
version = "0.12.0"
schema_version = 1
authors = ["François Mathey"]
description = "Silex language support"
repository = "https://github.com/fmathey/Silex"
languages = ["languages/silex"]
snippets = ["snippets/silex.json"]

[language_servers.silex]
name = "Silex LSP"
languages = ["Silex"]

[grammars.silex]
repository = "https://github.com/fmathey/Silex"
rev = "dba8af6e65e4dcbbd2b58e511ae72e7385a389b9"
