id = "silex"
name = "Silex"
version = "0.19.0"
schema_version = 1
authors = ["François Mathey"]
description = "Silex language support"
repository = "https://github.com/fmathey/Silex"
languages = ["languages/silex"]
snippets = ["snippets/silex.json"]

[language_servers.silex]
name = "Silex LSP"
languages = ["Silex"]

[grammars.silex]
repository = "https://github.com/fmathey/Silex"
rev = "55eea1d57c73bd4d9f3e5c0b57dd434a39d281ae"
