id = "silex"
name = "Silex"
version = "0.10.0"
schema_version = 1
authors = ["François Mathey"]
description = "Silex language support"
repository = "https://github.com/fmathey/Silex"
languages = ["languages/silex"]
snippets = ["snippets/silex.json"]

[language_servers.silex]
name = "Silex LSP"
languages = ["Silex"]

[grammars.silex]
repository = "https://github.com/fmathey/Silex"
rev = "b86d1ef5cf6f6f87835d1e8df2af38890605e124"
